#!/usr/bin/env bash
# MIZIGO — build the Rust pricing core to wasm and stage the artifacts.
#
#   rust/                            → the crate (see rust/README.md)
#   src/wasm/pricing_core.wasm      → raw wasm artifact (committed)
#   src/wasm/pricing_core_b64.ts    → base64 module the server imports at
#                                     runtime (committed; no fs needed on
#                                     Netlify, no Rust toolchain to deploy)
#
# Usage: scripts/build-wasm.sh [--skip-tests]
# Requires: rustup/cargo with the wasm32-unknown-unknown target installed
# (rustup target add wasm32-unknown-unknown).

set -euo pipefail
cd "$(dirname "$0")/.."

CARGO="${CARGO:-$HOME/.cargo/bin/cargo}"
if ! command -v "$CARGO" >/dev/null 2>&1 && [ ! -x "$CARGO" ]; then
  CARGO="cargo"
fi
if ! command -v "$CARGO" >/dev/null 2>&1; then
  echo "✗ cargo not found (install rustup, then: rustup target add wasm32-unknown-unknown)" >&2
  exit 1
fi

if [ "${1:-}" != "--skip-tests" ]; then
  echo "── cargo test (host target) ──────────────────────────────────────────"
  "$CARGO" test --manifest-path rust/Cargo.toml
fi

echo "── cargo build --release --target wasm32-unknown-unknown ────────────"
if ! "$CARGO" build --release --target wasm32-unknown-unknown --manifest-path rust/Cargo.toml; then
  echo "✗ build failed — is the wasm32-unknown-unknown target installed?" >&2
  echo "  run: rustup target add wasm32-unknown-unknown" >&2
  exit 1
fi

WASM="rust/target/wasm32-unknown-unknown/release/pricing_core.wasm"
mkdir -p src/wasm
cp "$WASM" src/wasm/pricing_core.wasm

# Base64 module generation. Named *_b64.ts (not pricing_core.wasm.ts) because
# an import specifier ending in ".wasm" resolves to the binary asset in
# webpack, and a ".wasm.ts" stem cannot be imported without
# allowImportingTsExtensions — see rust/README.md.
node -e '
const fs = require("fs");
const b = fs.readFileSync("src/wasm/pricing_core.wasm");
const s = b.toString("base64");
const chunks = s.match(/.{1,112}/g) || [];
const out = [
  "// GENERATED by scripts/build-wasm.sh — DO NOT EDIT BY HAND.",
  "// Base64 of the pricing-core wasm artifact (rust/ crate →",
  "// wasm32-unknown-unknown). Committed so deploys need no Rust toolchain;",
  "// rebuild with: scripts/build-wasm.sh",
  "export const PRICING_CORE_WASM_B64 =",
  ...chunks.map((c, i) => `  "${c}"${i === chunks.length - 1 ? ";" : " +"}`),
  "",
].join("\n");
fs.writeFileSync("src/wasm/pricing_core_b64.ts", out);
console.log(`   wrote src/wasm/pricing_core_b64.ts (${chunks.length} chunks)`);
'

echo "── artifacts ─────────────────────────────────────────────────────────"
ls -l src/wasm/pricing_core.wasm src/wasm/pricing_core_b64.ts | awk "{print \$5, \$9}"
echo "wasm size: $(wc -c < src/wasm/pricing_core.wasm) bytes"
echo "✓ pricing-core artifacts staged (commit src/wasm/* together with rust/)"
