#!/usr/bin/env python3
"""Transform prisma migrate-diff DDL into src/lib/ddl.ts (idempotent SQLite bootstrap).

Usage: bunx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > /tmp/ddl_raw.sql
       python3 scripts/make_ddl.py /tmp/ddl_raw.sql
"""
import re
import sys

src_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ddl_raw.sql"
out_path = "src/lib/ddl.ts"

with open(src_path) as f:
    sql = f.read()

# strip comment-only lines
sql = re.sub(r"^--.*$", "", sql, flags=re.M)
# make idempotent
sql = sql.replace('CREATE TABLE "', 'CREATE TABLE IF NOT EXISTS "')
sql = sql.replace('CREATE UNIQUE INDEX "', 'CREATE UNIQUE INDEX IF NOT EXISTS "')
sql = sql.replace('CREATE INDEX "', 'CREATE INDEX IF NOT EXISTS "')
# normalize whitespace: collapse blank runs
sql = re.sub(r"\n{2,}", "\n", sql).strip() + "\n"

# statements = split on ; at end of line
stmts = [s.strip() for s in sql.split(";\n") if s.strip()]

# sanity: no semicolons remain inside statements
for s in stmts:
    assert ";" not in s, f"semicolon inside statement: {s[:80]}"

body = ",\n".join(f"  {s!r}".replace("'", '"', 0) for s in [])  # placeholder, use backticks below

# use backtick template pieces? safer: JSON array of strings (no escaping games)
import json
arr = json.dumps(stmts, indent=2, ensure_ascii=False)

out = f'''// MIZIGO — SQLite DDL bootstrap (serverless cold start).
// GENERATED by scripts/make_ddl.py from prisma/schema.prisma — do not hand-edit.
// Regenerate after schema changes:
//   bunx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > /tmp/ddl_raw.sql
//   python3 scripts/make_ddl.py /tmp/ddl_raw.sql
// Used by ensureDB() when the runtime database is empty (e.g. Netlify /tmp).
// Idempotent: every statement uses IF NOT EXISTS, safe under cold-start races.

export const DDL_STATEMENTS: string[] = {arr};
'''

with open(out_path, "w") as f:
    f.write(out)

print(f"wrote {out_path}: {len(stmts)} statements")
